### ISSUE TITLE
EF6.2 "Value cannot be null. Parameter name: connection"

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#243] opened 2017-12-10 22:31 UTC
I'm using **MiniProfiler.EF6** 4.0.0-alpha9-00215, which is the latest version available on MyGet right now.

After calling `MiniProfilerEF6.Initialize()`, the following exception is thrown when querying the database:

```
Value cannot be null. Parameter name: connection
   at System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at System.Data.Entity.Infrastructure.DefaultDbProviderFactoryResolver.ResolveProviderFactory(DbConnection connection)
   at StackExchange.Profiling.EntityFramework6.EFProfiledDbProviderFactoryResolver.ResolveProviderFactory(DbConnection connection) in C:\projects\dotnet\src\MiniProfiler.EF6\EFProfiledDbProviderFactoryResolver.cs:line 28
   at System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderFactory(DbConnection connection)
   at System.Data.Entity.Core.Common.DbProviderServices.GetProviderFactory(DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.CreateConnection()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.AsNoTracking()
   at System.Data.Entity.Infrastructure.DbQuery`1.AsNoTracking()
```

I can only guess MiniProfiler wraps the database connection with a profiling layer which appears to contain a bug.

This worked fine in 4.0.0-alpha6-83. I am using .NET Framework 4.7.

**Comment by rlenders** [comment] 2017-12-11 19:04
This is caused by Entity Framework 6.2.0, which was released over a month ago.

**Comment by rlenders** [comment] 2017-12-11 19:11
Line 28 of `EFProfiledDbProviderFactoryResolver.cs` passes the `InnerConnection` to the inner factory resolver. At this point, `InnerConnection` is `null`, causing the exception to be thrown.

`InnerConnection` is `null` because the `ProfiledDbConnection` has already been disposed by Entity Framework 6.2.0. This does not happen when using EF 6.1.3.

**Comment by NickCraver** [comment] 2017-12-14 03:45
@rlenders how do you want to proceed here? I'd file this as a likely unintentional breaking change on the EF side (I've seen a few other reports of similar with the 6.2 release).

**Comment by rlenders** [comment] 2017-12-14 04:01
Do what you have to do, I reverted back to EF 6.1.3 so I can keep using MiniProfiler.

**Comment by elmcherqui** [comment] 2017-12-27 14:30
Hello,
I have exactly the same error , and i can confirm that this is due to EF 6.2.
Any workarounds ?

**Comment by rlenders** [comment] 2017-12-27 14:39
Actually, there's a third option, that is to use [my fork of MiniProfiler](https://github.com/rlenders/dotnet) instead.

**Comment by jdaigle** [comment] 2017-12-28 02:05
@rlenders any chance you could provide a minimal reproduction? I'm testing it with EF 6.2 and MiniProfiler.EF6 4.0.0-alpha9-00215 and it's working fine.

BTW, "4.0.0-alpha9-00215" isn't the latest build on MyGet. It's actually "4.0.0-alpha10-00219". But for some reason MyGet doesn't order them correctly. Or perhaps it's actually bug in the version numbering.

**Comment by elmcherqui** [comment] 2018-01-13 12:27
Hello ,
I'am using the : MiniProfiler.EF6 : 4.0.0-alpha9-00206
It was working really well the whole week , and when i installed / updated some package ( Azure storage and Azure Vault ) and the bug occures again : 

![picture](https://user-images.githubusercontent.com/12566542/34906021-4f04a8de-f85c-11e7-98da-7925fc438c3c.PNG)

Disabling the mini profiler removes the error , here you have my global.asax : 
![picture2](https://user-images.githubusercontent.com/12566542/34906063-0c1a3b3c-f85d-11e7-8e5c-66b5ad616670.PNG)

**Comment by elmcherqui** [comment] 2018-01-13 12:29
Hello ,
I'am using the : MiniProfiler.EF6 : 4.0.0-alpha9-00206
It was working really well the whole week , and when i installed / updated some package ( Azure storage and Azure Vault ) and the bug occures again : 

![picture](https://user-images.githubusercontent.com/12566542/34906021-4f04a8de-f85c-11e7-98da-7925fc438c3c.PNG)

Disabling the mini profiler removes the error , here you have my global.asax : 
![picture2](https://user-images.githubusercontent.com/12566542/34906063-0c1a3b3c-f85d-11e7-8e5c-66b5ad616670.PNG)

**Comment by jdaigle** [comment] 2018-01-13 13:25
@elmcherqui thanks. I just noticed that your stack trace matches the one at the top of the thread. The error occurs when EF is trying to run migrations on startup, which explains why I couldn’t reproduce, as it is not something I ever do. But hopefully now I can reproduce the issue and start working on a fix.

**Comment by NickCraver** [comment] 2018-01-14 18:18
@jdaigle Let me know what's needed here please, far better in your hands IMO.

**Comment by jdaigle** [comment] 2018-01-14 19:24
@NickCraver Luckily I was able to reproduce the error today. You have to use the "MigrateDatabaseToLatestVersion" database initializer (bleh).

I'm still tracking down exactly what changed in EF to break things (i.e. why it's passing around a disposed DbConnection), but so far I've come across this: https://github.com/aspnet/EntityFramework6/commit/8e1e169ddaf9bf20

They've added two `CloneConnection()` methods to `DbProviderServices`. Implementing appropriate overloads in our `EFProfiledDbProviderServices` seems to fix the problem.

If this is the correct fix then I guess that means we'll have to bump our dependency version to 6.2.0. But that's probably okay for v4?

**Comment by NickCraver** [comment] 2018-02-04 19:37
@jdaigle any more finding here? Should I ping the EF team and see what the motivation for these changes was?

**Comment by jdaigle** [comment] 2018-02-05 13:57
@NickCraver Overriding the two new "CloneDbConnection" methods is, I believe, all that is necessary to resolve this issue. I opened a pull request, which includes the dependency version bump.

**Comment by RudeySH** [comment] 2018-02-08 09:35
When will this become available on the NuGet pre-release feed?

**Comment by RudeySH** [comment] 2018-05-31 14:02
@NickCraver @jdaigle I noticed MiniProfiler v4.0.0 was released, but after updating and also updating EF from 6.1.3 to 6.2.0, I still get the same error.

```
[ArgumentNullException: Value cannot be null.
Parameter name: connection]
   System.Data.Entity.Utilities.Check.NotNull(T value, String parameterName) +44
   System.Data.Entity.Infrastructure.DefaultDbProviderFactoryResolver.ResolveProviderFactory(DbConnection connection) +23
   StackExchange.Profiling.EntityFramework6.EFProfiledDbProviderFactoryResolver.ResolveProviderFactory(DbConnection connection) +46
   System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderFactory(DbConnection connection) +51
   System.Data.Entity.Core.Common.DbProviderServices.GetProviderFactory(DbConnection connection) +34
   System.Data.Entity.Migrations.DbMigrator.CreateConnection() +22
   System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) +91
   System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration) +78
   System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context) +108
   System.Data.Entity.Internal.<>c__DisplayClassf`1.<CreateInitializationAction>b__e() +76
   System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action) +60
   System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization() +357
   System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c) +7
   System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input) +110
   System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action) +198
   System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase() +73
   System.Data.Entity.Internal.InternalContext.Initialize() +30
   System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +16
   System.Data.Entity.Internal.Linq.InternalSet`1.Initialize() +53
   System.Data.Entity.Internal.Linq.InternalSet`1.AsNoTracking() +18
   System.Data.Entity.Infrastructure.DbQuery`1.AsNoTracking() +46
```

**Comment by NickCraver** [comment] 2018-05-31 16:06
@RudeySH which version of MiniProfiler are you on? 4.0.0 isn't on NuGet quite yet, but MyGet has it.

**Comment by RudeySH** [comment] 2018-05-31 18:48
@NickCraver There's a 4.0.0 package on MyGet without a pre-release tag. That is the one I used. If I'm not mistaken that is the first release since this issue was supposedly fixed. I reverted back to 4.0.0-alpha9-00215 just now because that one doesn't have a dependency on EF 6.2.0.

**Comment by NickCraver** [comment] 2018-06-04 23:54
@ajcvickers Do you happen to know off-hand here what behavior change in 6.2 might be in play here? I assume we're missing an overload somewhere - trying to dig through but nothing standing out thus far.

**Comment by NickCraver** [comment] 2018-06-05 00:04
Ah okay I see why I wasn't seeing it - this looks like https://github.com/aspnet/EntityFramework6/issues/398 (fixed in latest `master`), indeed a regression in EF 6.2.

**Comment by NickCraver** [comment] 2018-06-05 00:08
@RudeySH This is an issue in EF, but there is a workaround here as well if you want to give it a try: https://github.com/aspnet/EntityFramework6/issues/398#issuecomment-346264914

**Comment by RudeySH** [comment] 2018-07-09 21:32
That workaround, passing an SQL connection to the base constructor of `DbContext`, seems to work!

```
public MyDbContext() : base(new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString), contextOwnsConnection: false)
```

I'm not sure if `contextOwnsConnection: false` is required. I don't know what the default value for that argument is, and I'm also not sure what it does.

**Comment by StuffOfInterest** [comment] 2018-07-09 22:22
Most likely, "contextOwnsConnection" will determine who handles disposing of the connection.  If the value is true, then I would expect the connection to be disposed when the context is disposed.  If the value is false, then whoever provided the connection will be responsible for disposing of it regardless of what happens to the context.  If the connection is provided by a dependency injection system then it should most likely be set to false.

**Comment by NickCraver** [comment] 2018-08-28 10:53
Going to close this out since it's really an EF issue (with hopefully a 6.3 release to resolve soon), but not much MiniProfiler can do here.

**Closed by NickCraver** 2018-08-28 10:53 UTC
Labels: blocked

**Comment by RudeySH** [comment] 2019-12-02 17:00
Entity Framework 6.3 has released and the issue was fixed, so the workaround above is no longer necessary when using EF6.3. Furthermore, I advise against using the workaround when you're on EF6.2, because it causes other issues (see #392).
