### ISSUE TITLE
QuotaExceededError: The quota has been exceeded

### ISSUE THREAD

**Issue by xt0rted** [MiniProfiler/dotnet#141] opened 2016-10-25 02:05 UTC
I just hit this error with mobile safari and private browsing. I'm running version 3.2.0.157 which is the latest on NuGet. I'm guessing this is the same as https://github.com/MiniProfiler/rack-mini-profiler/issues/169. Is there a newer version that fixes this?

**Comment by NickCraver** [comment] 2016-11-22 11:14
I'll make sure this is fixed in 2.x. The problem is that Safari in private mode just pretends localStorage is there and full. It's an incredibly stupid thing for them to do, and it's bitten almost everyone I know that's used localStorage at all. Since it's a `ui` lib issue, just using latest should fix it (it's a submodule). I'll make sure that's the case in this vNext work though.

**Comment by NickCraver** [comment] 2017-02-16 05:03
This is fixed with additional checks in v4. Thanks for the report!

**Closed by NickCraver** 2017-02-16 05:03 UTC
Labels: bug
