### ISSUE TITLE
Issues with IE8 because of addEventListener

### ISSUE THREAD

**Issue by aramacciotti** [MiniProfiler/dotnet#457] opened 2020-02-11 11:51 UTC
includes.min.js has some addEventListener instance that are not working with IE8 (or IE11 with emulation 8) and that prevent to use MiniProfiler to profile application that require to be navigated with such a browser setting.
The error raise at **includes.min.js (2,43190)** (Object doesn't support property or method 'addEventListener').
Can it be managed by checking if supported and otherwise use attachEvent sintax?

**Comment by NickCraver** [comment] 2020-02-11 12:00
This is expected behavior if you're on a release _after_ 4.1.0 (4.2.0 drops support for IE 11 but hasn't been released to NuGet yet - this was dropped in https://github.com/MiniProfiler/dotnet/pull/442).

It's simple untenable to continue supporting IE 11, other bits which aren't reasonable to accomplish in older browsers are things like themes (see #451). This will transition MiniProfier to using CSS variables so...it wouldn't render well in IE 11 or lower anyway, even if the scripts worked.

Overall, my recommendation is that if you're limited to IE 11, continue using MiniProfiler 4.1.x or lower.

**Comment by aramacciotti** [comment] 2020-02-11 12:41
Actually I'm using v.4.1.0, possibly have I to downgrade it more?

```
  <package id="MiniProfiler" version="4.1.0" targetFramework="net48" />
  <package id="MiniProfiler.Shared" version="4.1.0" targetFramework="net48" />
```

**Comment by NickCraver** [comment] 2020-02-12 02:27
Hmm, if you're in IE 8 mode, I have no idea what version may or may not work. We strung along with IE 11 support for a while (with no specific intent for IE 8), but since have dropped even that. If 4.0.0 doesn't work, you're looking at the 3.x line...but a lot has changed and improved since those builds (especially around async).

**Comment by aramacciotti** [comment] 2020-02-12 07:07
I'll try 4.0.0. Essentially what currently is not working is **addEventListener**

**Comment by aramacciotti** [comment] 2020-02-12 12:39
Unfortunately v.4.0.0 already was not compatible with IE11 (8 mode). I have to use older versions

**Comment by NickCraver** [comment] 2020-04-04 13:24
Going to close this out to cleanup - for anyone finding this later: indeed, MiniProfiler does not support this from v4 onwards.

**Closed by NickCraver** 2020-04-04 13:24 UTC
