### ISSUE TITLE
Unable to get query trace for WPF Application

### ISSUE THREAD

**Issue by guillaumejay** [MiniProfiler/dotnet#438] opened 2019-11-20 15:12 UTC
Hello,

I have the same issue (.net Framework 4.7), WPF Application.
     MiniProfilerEF6.Initialize is the first line in my program.cs/main function.

And I'm getting that : (I'm creating/starting the profiler when the user clicks on a button)
AGP00038 at 20/11/2019 15:09:43
Activate all 328 794,3ms
>> Activation 328 770,8ms (sql = 34 525,9ms in 36824 cmds)
>> Counting 21,3ms (sql = 17,3ms in 3 cmds)

(you can see why i'm interested in getting query details...)

_Originally posted by @guillaumejay in https://github.com/MiniProfiler/dotnet/issues/340#issuecomment-556046190_

**Comment by NickCraver** [comment] 2019-11-24 12:53
I'm no familiar with WPF so...how are you trying to display the profiler? What makes you think it is or isn't there?

Or am I misreading this and you're looking at the text-based version in some output, and the issue is the default tree doesn't include all query details?

**Comment by guillaumejay** [comment] 2019-11-24 17:11
Yes , I'm using the RenderPlainText() function, and not getting the query details.

**Comment by NickCraver** [comment] 2019-11-25 04:13
There's not really a built-in command for this since commands are all over the place, but if you wanted to loop over all timings and output something, here's an example of how to do so:
```c#
var sb = new StringBuilder();
foreach (var timing in MiniProfiler.Current.GetTimingHierarchy())
{
    if (timing.HasCustomTimings)
    {
        sb.Append(timing.Name).AppendLine(":");
        foreach (var type in timing.CustomTimings.Keys)
        {
            sb.Append("  ").Append(type).Append(":").AppendLine();
            foreach (var customTiming in timing.CustomTimings[type])
            {
                sb.Append("    Type:").AppendLine(customTiming.ExecuteType);
                sb.Append("    Stack Trace:").AppendLine(customTiming.StackTraceSnippet);
                sb.Append("    Start (ms):").AppendLine(customTiming.StartMilliseconds.ToString());
                sb.Append("    Duration (ms):").AppendLine(customTiming.DurationMilliseconds.ToString());
                if (customTiming.FirstFetchDurationMilliseconds.HasValue)
                {
                    sb.Append("    First Fetch (ms):").AppendLine(customTiming.FirstFetchDurationMilliseconds.ToString());
                }
                sb.Append("    Command:").AppendLine(customTiming.CommandString);
            }
        }
    }
}
return sb.ToString();
```

**Comment by guillaumejay** [comment] 2019-11-28 07:29
Thanks, it works.

I was wrongly believing that RenderPlainText was doing all the work we get in the WebUI :)

**Comment by NickCraver** [comment] 2020-04-04 15:08
Great! Closing out to cleanup :)

**Closed by NickCraver** 2020-04-04 15:08 UTC
Labels: needs-info
