### ISSUE TITLE
JSON serializer throws 500 when id is empty

### ISSUE THREAD

**Issue by fantasticfears** [MiniProfiler/dotnet#454] opened 2020-01-28 09:46 UTC
I inject miniprofiler in the client-side by a script.

    const script = document.createElement('script');
    script.id = "mini-profiler";
    script.src = "/profiler/includes.min.js";
    script.async = true;
    script.dataset.ids = "";
    script.dataset.version = "4.1.0+202001271656";
    script.dataset.path = "/profiler/";
    script.dataset.position = "BottomLeft";
    script.dataset.authorized = "true"
    script.dataset.maxTraces = "10";
    script.dataset.toggleShortcut = "Alt+P";
    script.dataset.trivialMilliseconds = "2.0";
    script.dataset.ignoredDuplicateExecuteTypes = "Open,OpenAsync,Close,CloseAsync";

    document.body.appendChild(script);

This will yield a 500 with `System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.Guid]. Path: $.Id | LineNumber: 0 | BytePositionInLine: 8.` because the request is `{Id: ""}`
The project has `Nullable` set to true.

https://github.com/MiniProfiler/dotnet/blob/95eddc7d57cee9f377419733bf18e76f3e5879e5/src/MiniProfiler.AspNetCore/MiniProfilerMiddleware.cs#L325-L327

System.Text.Json is a little bit more lenient.

**Comment by NickCraver** [comment] 2020-01-29 01:53
This has the same root cause as #449, so I just pushed a fix for both. Ultimately it's `"".split(",") => [""]`, or in other words: an array with a single empty ID, rather than an empty array...because I forgot how JavaScript worked there for a hot minute while refactoring last time.

Anyway, fixed for the next release (it'll be up on MyGet shortly) - thanks for the report!

**Closed by NickCraver** 2020-01-29 01:53 UTC

**Comment by hemiaoio** [comment] 2020-04-16 03:10
Is there a library connection for myget? Or when will the next version be released?
