### ISSUE TITLE
Any objection to returning a 404 instead of "hidden"?

### ISSUE THREAD

**Issue by cottsak** [MiniProfiler/dotnet#211] opened 2017-08-31 08:10 UTC
For the unauthenticated requests to `/mini-profiler-resources/results`? eg https://github.com/MiniProfiler/dotnet/blob/e57ba9f96eb0267cf1f99dc952938ad8142d7d3f/src/MiniProfiler/MiniProfilerHandler.cs#L251

I'll push the PR if it's a good idea.
I just don't like what `"hidden"` reveals: namely that I'm using MiniProfiler. 404 is often cited by InfoSec folks as the preference to 401 since it reveals the same as if there was nothing at that URI.

Thoughts?

**Comment by NickCraver** [comment] 2017-09-04 00:44
If we return a 404 here, we can't differentiate between a missing profiler (e.g. not in cache) and a profiler you can't access, so there's a loss of functionality/resolution doing this.

**Comment by NickCraver** [comment] 2017-09-04 01:44
@cottsak The client (e.g. out JavaScript) can't tell what's denied vs. what's missing, this will be a functionality loss and make even basic debugging much harder.

**Comment by cottsak** [comment] 2017-09-04 05:03
@NickCraver Why can't the js client treat the 401/404 responses as the same? ie. "this doesn't work as I expected", and then hide the UI/profiling, etc?

**Comment by NickCraver** [comment] 2017-09-04 10:33
The problem isn't treating them the same, it's trying to tell them apart when debugging anything - I'll look into make this an *option*, but I can't say that the fact you're using MiniProfiler reveals anything of value in the first place.

**Comment by dchaib** [comment] 2018-03-02 12:27
I also have an issue (more philosophical than blocking though) with the 401 status code, but I don't think 404 is actually better.

On our websites, we are profiling all requests in production without showing the UI, so it means on every page request we have in the browser at least one request returning 401, which bugs me. To me, 401 would rather mean that the results couldn't be sent because the server refused the request, which is not really true. On top of that, I don't like seeing errors when everything is working as intended. :)

My intent is to post the results and only that. I don't really care for the UI in this case. Wouldn't it make sense to return simply 200? After all, the request is doing 2 things at the same time if I understand well:
- posting the results, which is available (so not 404), authorized (so not 401) and processed without issue (so 200),
- optionally displaying the results, which is not requested in this case.
Does it make sense to determine the status code based on the optional part?

**Comment by NickCraver** [comment] 2018-08-28 10:49
I thought I had follow-up on this - the behavior now is to not include the JavaScript if not authorized...so we shouldn't be making that request from the user anymore, meaning no 401s. I do disagree that a 401 isn't correct though. It's trying to access a thing the server says is forbidden, that's *exactly* what a 401 is for. Hopefully with the other tweaks this is now a non-issue for most or all, though.

**Comment by NickCraver** [comment] 2018-11-11 15:40
No changes here and the other behaviors have gone in that mostly remove this case...going to close this out to cleanup. We can discuss if it comes up as an issue again.

**Closed by NickCraver** 2018-11-11 15:40 UTC
Labels: enhancement
