### ISSUE TITLE
Certain AJAX requests do not show up until page refresh

### ISSUE THREAD

**Issue by LangdalP** [MiniProfiler/dotnet#247] opened 2017-12-15 10:02 UTC
Hi,

I run MiniProfiler (just the base version, not MVC) on an ASP.NET MVC site, and most things work as they should. However, some pages use React and therefore start fetching data around the time that my browser is done rendering the page. Frequently, these requests do not show up in the MiniProfiler window until I go to another page, or refresh the page.

Also, when inspecting the POST requests made to ```~/mini-profiler-resources/results```, I do **not** see a request that corresponds with these late AJAX calls. So it seems to me that the client never asks for any results for these calls. However, if I manually open a new tab and go to ```~/mini-profiler-resources/results```, I get the result of the last AJAX request.

Is this the expected behaviour? Is there some work-around I can use to get these AJAX calls to show up in MiniProfiler?

**Comment by NickCraver** [comment] 2018-02-04 19:54
What are you using for AJAX calls? React isn't dependent (AFAIK) but generally recommends jQuery, which we do hook into.

On the requests coming back, you should see a `X-MiniProfiler-Ids` header. This is what we parse and fetch MiniProfiler's for. If that's not on the AJAX request: the problem is before headers. If the header is on the request, that means we're not listening for it. So let's see where the issue lies first.

**Comment by LangdalP** [comment] 2018-02-05 14:42
We use [xhr](https://www.npmjs.com/package/xhr), but I have now tested with jQuery as well.

In both cases, the response does contain an `X-MiniProfiler-Ids` header. However, when I use jQuery, the late AJAX requests do indeed show up in the MiniProfiler overlay. So I suppose that means that you are not listening to it. I have not dug into the code yet, so I am not sure exactly how you are listening specifically for jQuery requests. Is it possible to make the "listener" more general, or does it depend on jQuery-specific capabilities?

I am open to contributing the changes needed to make this work with xhr as well, if you think it is possible.

**Comment by Postlagerkarte** [comment] 2018-02-05 14:50
I am having the issue when using [axios ](https://www.npmjs.com/package/axios) - it uses xhr request which are not displayed by the profiler.  The response does not include the `X-MiniProfiler-Ids`.

**Comment by LangdalP** [comment] 2018-02-05 15:24
I have now seen that the MiniProfiler overlay "listens" to requests by overriding the window.fetch function. I think there is nothing stopping us from also overriding the relevant XMLHttpRequest function(s). This would make the overlay support requests made with both APIs. I will probably start testing this locally soon. Would you be open to such a pull request?

**Comment by Postlagerkarte** [comment] 2018-02-05 17:11
Seems like the AngularJs if branch does the trick - as a workaround setting the window.angular variable to a dummy helps for now.

**Comment by NickCraver** [comment] 2018-02-06 00:12
I'm certainly open to making that `if` cover more cases if valid. What's a good check for axios? For example, would this work?
```js
if ((window.angular || window.axios) && typeof (XMLHttpRequest) != 'undefined') {
```

**Comment by Postlagerkarte** [comment] 2018-02-06 08:24
What problems would it cause to just make it check for  `(XMLHttpRequest) != 'undefined'` without checking for specific applications?

**Comment by LangdalP** [comment] 2018-02-06 08:28
I was thinking the same thing. If you override fetch and XMLHttpRequest.prototype.send, that would cover all ajax calls, would it not?

**Comment by NickCraver** [comment] 2018-02-06 11:55
The problem with doing it unconditionally (effectively all browsers have this) is it can cause unexpected side-effects for some people. There's good reason the prototype library approach in general kinda went by the wayside. It's not a fundamental problem to have objects and prototypes, but overriding shared components and breaking expectations does create trouble with it breaks something downstream. 

I'm very hesitant to do such a thing, but I'll reach out and see what the general thought on this is today. I'm not familiar with enough JS frameworks (I think we're up to 3-4 billion now?) to know which it may cause crazy problems with.

**Comment by NickCraver** [comment] 2018-02-06 12:04
For anyone finding this issue, the relevant code section is here: https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/ui/includes.js#L583

**Comment by Kukkimonsuta** [comment] 2018-02-06 12:37
Since you can't ever cover all the frameworks, I'd make it a switch.

* Compat (default) - current way covering most popular frameworks in highly compatible way (even though implementation for `angular` and `fetch` are potentially breaking even now)
* Generic - ignore all framework switches and replace both `XMLHttpRequest.prototype.send` and `fetch`
* Manual - don't touch anything, let user submit ids manually

This way you won't break any existing users, but people who discover missing timings can try resolving it with simple switch.

In time you might be forced to switch to `Generic` or `Manual` as default, because you might not be able to check for specific frameworks thanks to modules and module bundlers (generally you don't introduce global variables when working with modules).

**Comment by NickCraver** [comment] 2018-02-11 15:17
I pushed an immediate fix for `window.axios` and `window.xhr` for the moment while figuring out a longer-term (perhaps nothing more complicated is needed at the moment). The problem is that `XMLHttpRequest` isn't even *the* way to do AJAX anymore - now we have Fetch APIs as well. We'd need to attach to both, ensure no duplication and framework interference. So, that's not a quick fix - what I've done is quickly alleviate pain presented here via the proposed JS above - it'll be on MyGet shortly and I hope NuGet.org this week.

@Kukkimonsuta thanks for chiming it with ideas - I'll definitely be thinking about this route first in the overall coverage approach.

**Closed by NickCraver** 2018-02-11 15:17 UTC

**Comment by LangdalP** [comment] 2018-02-12 10:31
Sorry for the late reply. I don't believe that axios defines window.axios and I don't think xhr does it either.

**Comment by vamsitp** [comment] 2018-02-19 18:36
Setup: `Asp.Net Core (MVC) WEB App with React` + `Asp.NET Core (MVC) API App`. 
1. Added `MiniProfiler.AspNetCore.Mvc` (tried with `alpha`/`beta` releases) to both `WEB` and `API` projects 
2. Client-side (`React`) component within the `WEB App` makes a call to a C# `Controller` within the same `WEB App` that in turn calls the `API App`
3. `API App` returns a response along with some additional header that contain the API-MiniProfiler's compressed JSON (similar to [this](https://github.com/ericpopivker/miniprofiler-web-api#miniprofiler-for-web-api))
4. `WEB App`'s `Controller` reads the custom-header from the `Response`, deserializes it (say `var apiAppMiniProfiler`) and adds it to it's own MiniProfiler's current instance (`webAppMiniProfiler.AddProfilerResults(apiAppMiniProfiler)`)
5. MiniProfiler UI on the `WEB App` does not reflect the `clide-side`-invoked calls
    1. Move to a different page, and you see the previous (client-side) calls in MiniProfiler UI
    2. (OR) Hit REFRESH on the browser, and you can see the `client-side` calls
6. Tried adding the raw `ClientTimingHelper.InitScript` script explicitly in `Shared/Layout` cshtml, with no luck

**Comment by wongJonathan** [comment] 2018-06-25 18:18
Has there been any fix yet? I'm currently using `axios` to call my api controller and it outputs to the console correctly but not in the browser. Would love an update on any changes or workarounds!
