### ISSUE TITLE
Areas in Core 2.0

### ISSUE THREAD

**Issue by NonInspirationalName** [MiniProfiler/dotnet#255] opened 2018-01-12 17:22 UTC
I added miniprofiler to my MVC core 2.0 project and everything was fine. I moved my controllers into an area, and the profiler stopped working. The tag helper is included in the shared view, but emits no output. Other specific output in the _layout page is displayed properly, which means that the layout file is actively being used.

As soon as the URI path has an area AND controller in it, then it stops showing. 

eg: 
/somecontroller - fine
/somearea - fine
/somecontroller/someaction - fine
/somearea/somecontroller - stops working

I have tried to find anything in the source that might be actively blocking this but I could not find it.

Is there some special setup required to get miniprofiler to play nicely with areas?

**Comment by NickCraver** [comment] 2018-02-06 00:25
To be honest I'm not 100% sure here, but I think there are a few bugs manifesting in the same problem (lack of prefixes). What needs to happen is my adding an area to the samples project and seeing what's up. I'll try and do that this week.

**Comment by NickCraver** [comment] 2018-02-11 16:20
Related issue: #230 (notes for me!)

**Comment by NickCraver** [comment] 2018-02-11 16:31
I added some bits to the sample all and can't reproduce this - do you have a link to the project or anything?

**Comment by NickCraver** [comment] 2018-04-27 14:10
Closing this out with no info to go on, AFAIK this isn't an issue in the latest release.

**Closed by NickCraver** 2018-04-27 14:10 UTC
Labels: needs-info
